creazione di schedarii di paginatura solu nant’à una partizione cifrata o un lettore cifratu di u sistema.</entry>
		<entry lang="co" key="SYS_ENC_HIBERNATION_PREVENTED">Un sbagliu o una incumpatibilità impedisce VeraCrypt di cifrà u schedariu d’invernazione. In cunsequenza, l’invernazione hè stata impedita.\n\nNota : Quandu un urdinatore si mette in invernazione (o entre in u modu d’ecunumia d’energia), u cuntenutu di a so memoria di u sistema hè scrittu in un schedariu d’allucamentu chì stà nant’à u lettore di u sistema. VeraCrypt ùn seria micca capace d’impedisce e chjavi di cifratura è u cuntenutu di i schedarii sensibile aperti i memoria RAM d’esse arregistrati micca cifrati nant’à u schedariu d’invernazione.</entry>
		<entry lang="co" key="HIDDEN_OS_HIBERNATION_PREVENTED">L’invernazione hè stata impedita.\n\nVeraCrypt ùn permette micca l’invernazione nant’à i sistemi operatorii chì impieganu una partizione addiziunale di piccera. Sappiate chì a partizione di piccera hè scumparta da l’ingannu è da u sistema piattatu. In cunsequenza, per impedisce e sfughjime di dati è i prublemi à l’esce di l’invernazione, VeraCrypt hà da impedisce u sistema piattatu di scrive in a partizione scumparta di piccera è di mettesi in invernazione.</entry>
		<entry lang="co" key="VOLUME_MOUNTED_AS_DRIVE_LETTER_X_DISMOUNTED">U vulume VeraCrypt chì era muntatu cum’è %c: hè statu smuntatu.</entry>
		<entry lang="co" key="MOUNTED_VOLUMES_DISMOUNTED">I vulumi VeraCrypt sò stati smuntati.</entry>
		<entry lang="co" key="VOLUMES_DISMOUNTED_CACHE_WIPED">I vulumi VeraCrypt sò stati smuntati è l’impiatta di a parolla d’intesa hè stata nettata.</entry>
		<entry lang="co" key="SUCCESSFULLY_DISMOUNTED">Smuntatu currettamente</entry>
		<entry lang="co" key="CONFIRM_BACKGROUND_TASK_DISABLED">AVERTIMENTU : S’è a tacca di sfondulu VeraCrypt hè disattivata, quelle funzioni seranu inattive :\n\n1) Tasti di scelta rapida\n2) Smuntatura autumatica (per indettu, à a scunnessione, a cacciatura invuluntaria d’apparechju ospite, cumportu d’attesa, ecc.)\n3) Muntatura autumatica di i vulumi favuriti\n4) Nutificazioni (per indettu, quandu un dannu hè impeditu nant’à u vulume piattatu)\n5) Icona di u spaziu di nutificazione\n\nNota : Pudete piantà a tacca di sfondulu à ogni mumentu da un cliccu dirittu nant’à l’icona VeraCrypt in u spaziu di nutificazione è selezziunendu « Esce ».\n\nDa veru, vulete disattivà ab’eternu a tacca di sfondulu VeraCrypt ?</entry>
		<entry lang="co" key="CONFIRM_NO_FORCED_AUTODISMOUNT">AVERTIMENTU : S’è st’ozzione hè disattivata, i vulumi chì cuntenenu schedarii o cartulari aperti ùn puderanu micca esse smuntati autumaticamente.\n\nDa veru, vulete disattivà st’ozzione ?</entry>
		<entry lang="co" key="WARN_PREF_AUTO_DISMOUNT">AVERTIMENTU : I vulumi chì cuntenenu schedarii o cartulari aperti ùn seranu MICCA smuntati autumaticamente.\n\nPer impedisce què, attivate quella ozzione in sta finestra di dialogu : « Sfurzà a smuntatura autumatica ancu s’è u vulume cuntene schedarii o cartulari aperti »</entry>
		<entry lang="co" key="WARN_PREF_AUTO_DISMOUNT_ON_POWER">AVERTIMENTU : S’è a batteria di l’urdinatore purtavule hè debule, Windows pò omette di mandà i messaghji adequati à l’appiecazioni chì funziuneghjanu quandu l’urdinatore entre in u modu d’ecunumia d’energia. In cunsequenza, VeraCrypt pò fiascà à smuntà autumaticamente i vulumi in tale casi.</entry>
		<entry lang="co" key="NONSYS_INPLACE_ENC_RESUME_PROMPT">Avete pianificatu u tr